import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerEchoTool } from './echo.js';
import { registerConfigureFiltersTool } from './configure-filters.js';
import { registerRefreshDependenciesTool } from './refresh-dependencies.js';
import { registerReadJarEntryTool } from './read-jar-entry.js';
import { registerLoadProjectTool } from './load-project.js';
import { registerUnloadProjectTool } from './unload-project.js';
import { registerListProjectsTool } from './list-projects.js';
import { registerSetDefaultProjectTool } from './set-default-project.js';
import { registerGetProjectMetadataTool } from './get-project-metadata.js';
import { registerListPackagesTool } from './list-packages.js';
import { registerListClassesTool } from './list-classes.js';
import { registerReadSourceTool } from './read-source.js';
import { registerSearchClassesTool } from './search-classes.js';
import { registerLocateInSourceTool } from './locate-in-source.js';
import { registerFindDefinitionTool } from './find-definition.js';
import { registerFindReferencesTool } from './find-references.js';
import { registerListMembersTool } from './list-members.js';
import { registerGetSymbolInfoTool } from './get-symbol-info.js';
import { registerFindImplementationsTool } from './find-implementations.js';
import { registerTypeHierarchyTool } from './type-hierarchy.js';
import { registerSearchSymbolsTool } from './search-symbols.js';
import { registerAddStudyJarTool } from './add-study-jar.js';
import { registerRemoveStudyJarTool } from './remove-study-jar.js';
import { registerListStudyJarsTool } from './list-study-jars.js';
import { registerConfigureStudyJarTool } from './configure-study-jar.js';
import { registerReadMemberTool } from './read-member.js';
import { registerCreateProjectTool } from './create-project.js';
import { registerRemoveProjectTool } from './remove-project.js';
import { registerSetActiveChildTool } from './set-active-child.js';
import { registerSetActiveProjectTool } from './set-active-project.js';
import { registerGetProjectInfoTool } from './get-project-info.js';
import { registerGetMemberInfoTool } from './get-member-info.js';
import { registerAddFabricModTool } from './add-fabric-mod.js';
import { registerRemoveProjectMemberTool } from './remove-project-member.js';
import { registerRefreshProjectTool } from './refresh-project.js';
import { registerRefreshProjectMembersTool } from './refresh-project-members.js';

export function registerAllTools(server: McpServer): void {
	registerEchoTool(server);
	registerConfigureFiltersTool(server);
	registerRefreshDependenciesTool(server);
	registerReadJarEntryTool(server);
	registerLoadProjectTool(server);
	registerUnloadProjectTool(server);
	registerListProjectsTool(server);
	registerSetDefaultProjectTool(server);
	registerGetProjectMetadataTool(server);
	registerListPackagesTool(server);
	registerListClassesTool(server);
	registerReadSourceTool(server);
	registerSearchClassesTool(server);
	registerLocateInSourceTool(server);
	registerFindDefinitionTool(server);
	registerFindReferencesTool(server);
	registerListMembersTool(server);
	registerGetSymbolInfoTool(server);
	registerFindImplementationsTool(server);
	registerTypeHierarchyTool(server);
	registerSearchSymbolsTool(server);
	registerAddStudyJarTool(server);
	registerRemoveStudyJarTool(server);
	registerListStudyJarsTool(server);
	registerConfigureStudyJarTool(server);
	registerReadMemberTool(server);
	registerCreateProjectTool(server);
	registerRemoveProjectTool(server);
	registerSetActiveChildTool(server);
	registerSetActiveProjectTool(server);
	registerGetProjectInfoTool(server);
	registerGetMemberInfoTool(server);
	registerAddFabricModTool(server);
	registerRemoveProjectMemberTool(server);
	registerRefreshProjectTool(server);
	registerRefreshProjectMembersTool(server);
}
